set VERSION 21

set init_design_uniquify 1

# this variable points to the file that was generated by logic synthesis
set init_verilog {../synthesis/sha256.netlist.v}
set init_design_netlisttype {Verilog}
set init_design_settop {1}
# this is the name of the top level module of the design
set init_top_cell {sha256}

set DB_PATH "../db/"					
set LEF_PATH "../lef/scaled/"
set TLEF_PATH "../techlef/"

# lef files that define the technology and the standard cell library
set CELL_LEF "$LEF_PATH/asap7sc7p5t_28_L_4x_220121a.lef $LEF_PATH/asap7sc7p5t_28_SL_4x_220121a.lef $LEF_PATH/asap7sc7p5t_28_R_4x_220121a.lef"
set TECH_LEF $TLEF_PATH/asap7_tech_4x_201209.lef

# tech lef first, cell lef later
set init_lef_file "$TECH_LEF $CELL_LEF"

# floorplan related variables
set fp_core_cntl {aspect}
set fp_aspect_ratio {1.0000}
set extract_shrink_factor {1.0}
set init_assign_buffer {0}
set init_pwr_net {VDD}
set init_gnd_net {VSS}

# here starts the timing libraries
# we don't have a cpf file because the design has a single power domain
set init_cpf_file {}
# the mmmc file has the constraints
set init_mmmc_file {sha256.mmmc}

# this will trigger the loading of the libraries and the design
init_design
